sudo: required
language: c

env:
  - CABALVER=1.16 GHCVER=7.4.1
  - CABALVER=1.16 GHCVER=7.4.2
  - CABALVER=1.16 GHCVER=7.6.1
  - CABALVER=1.16 GHCVER=7.6.2
  - CABALVER=1.18 GHCVER=7.6.3
  - CABALVER=1.18 GHCVER=7.8.1
  - CABALVER=1.18 GHCVER=7.8.2
  - CABALVER=1.18 GHCVER=7.8.3
  - CABALVER=1.18 GHCVER=7.8.4
  - CABALVER=1.22 GHCVER=7.10.1
  - CABALVER=1.22 GHCVER=7.10.2
  - CABALVER=1.22 GHCVER=7.10.3
  - CABALVER=1.24 GHCVER=8.0.1

  - CABALVER=1.22 GHCVER=7.4.2 QC=QuickCheck-2.5.1.1
  - CABALVER=1.22 GHCVER=7.6.3 QC=QuickCheck-2.6
  - CABALVER=1.22 GHCVER=7.8.4 QC=QuickCheck-2.6

  - CABALVER=1.18 GHCVER=7.8.4 HU=HUnit-1.3.1.2
  - CABALVER=1.22 GHCVER=7.10.3 HU=HUnit-1.3.1.2
  - CABALVER=1.24 GHCVER=8.0.1 HU=HUnit-1.3.1.2

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
  - ghc --version
  - cabal --version
  - travis_retry cabal update
  - if [ -n "$QC" ]; then cabal install $QC; fi
  - if [ -n "$HU" ]; then cabal install $HU; fi

script:
  - ./travis.sh
